<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-white leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="flex flex-col h-full px-8 py-5">
        <div class="flex justify-between w-full shadow rounded-full overflow-hidden">
            <div id="dashboard-all" onclick="fetchCandidate(this);" data-href="{{ route('dashboard.candidate', '') }}" class="flex space-x-4 px-4 py-2 w-full justify-center cursor-pointer text-white bg-gray-200 bg-pink-600">
                <div class="font-semibold">
                    Applicant List
                </div>
                <div id="dashboard-all-count" class="flex items-center font-semibold bg-white rounded-full px-2 text-xs text-gray-800">
                    0
                </div>
            </div>
            <div id="dashboard-kiv" onclick="fetchCandidate(this);" data-href="{{ route('dashboard.candidate', 'KIV') }}" class="flex space-x-4 px-4 py-2 w-full justify-center cursor-pointer bg-gray-200 hover:bg-gray-300">
                <div class="font-semibold">
                    KIV List
                </div>
                <div id="dashboard-kiv-count" class="flex items-center font-semibold bg-white rounded-full px-2 text-xs text-gray-800">
                    0
                </div>
            </div>
            <div id="dashboard-interview" onclick="fetchCandidate(this);" data-href="{{ route('dashboard.candidate', 'INT') }}" class="flex space-x-4 px-4 py-2 w-full justify-center cursor-pointer bg-gray-200 hover:bg-gray-300">
                <div class="font-semibold">
                    Ready for Interview
                </div>
                <div id="dashboard-interview-count" class="flex items-center font-semibold bg-white rounded-full px-2 text-xs text-gray-800">
                    0
                </div>
            </div>
            <div id="dashboard-done" onclick="fetchCandidate(this);" data-href="{{ route('dashboard.candidate', 'DONE') }}" class="flex space-x-4 px-4 py-2 w-full justify-center cursor-pointer bg-gray-200 hover:bg-gray-300">
                <div class="font-semibold">
                    Completed
                </div>
                <div id="dashboard-done-count" class="flex items-center font-semibold bg-white rounded-full px-2 text-xs text-gray-800">
                    0
                </div>
            </div>
        </div>
        <hr class="my-4">
        <div id="dashboard-candidate-list" class="flex flex-col space-y-4 flex-1 overflow-auto">
            <!--Generated by JQuery-->
        </div>
    </div>

    @push('scripts')
    <script>
        $(document).ready(function(){
            countCandidate();
            $('#dashboard-all').click();
        });

        function countCandidate() {
            var url = "{{ route('dashboard.count') }}";

            $.ajax({
                url : url,
                success : function(response) {
                    if (response!='') {
                        $('#dashboard-all-count').html(response.applicantCnt);
                        $('#dashboard-kiv-count').html(response.kivCnt);
                        $('#dashboard-interview-count').html(response.interviewCnt);
                        $('#dashboard-done-count').html(response.doneCnt);
                    }
                }
            });
        }

        function fetchCandidate(obj) {
            deselectAll();
            $('#'+obj.id).addClass('bg-pink-600 text-white');
            $('#'+obj.id).removeClass('hover:bg-gray-300');
            var url = $('#'+obj.id).attr('data-href');
            $('#loading').removeClass('hidden');

            $.ajax({
                url : url,
                success : function(response) {
                    if (response!='') {
                        $('#dashboard-candidate-list').html(response.result);
                        $('#loading').addClass('hidden');
                    }
                }
            });
        }

        function deselectAll() {
            $('#dashboard-all').removeClass('bg-pink-600 text-white');
            $('#dashboard-kiv').removeClass('bg-pink-600 text-white');
            $('#dashboard-interview').removeClass('bg-pink-600 text-white');
            $('#dashboard-done').removeClass('bg-pink-600 text-white');

            $('#dashboard-all').addClass('hover:bg-gray-300');
            $('#dashboard-kiv').addClass('hover:bg-gray-300');
            $('#dashboard-interview').addClass('hover:bg-gray-300');
            $('#dashboard-done').addClass('hover:bg-gray-300');
        }
    </script>
    @endpush
</x-app-layout>
